CREATE TABLE PERSON
    (
        ID INTEGER NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        LOCATION VARCHAR(255) NOT NULL,
        BIRTH_DATE DATE,
        PRIMARY KEY (ID)
);

INSERT INTO PERSON
    (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10001, 'Jasim Ahmed', 'KARACHI', '1994-12-26');

INSERT INTO PERSON
    (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10002, 'Rameesh ahmed', 'Sukkhar', '2008-09-02');

INSERT INTO PERSON
    (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10003, 'Qasim Ahmed', 'Hyderabad', '2021-12-04');

INSERT INTO PERSON
    (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10004, 'Sultan Ahmed', 'Quetta', '2002-12-04');

INSERT INTO PERSON
    (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10005, 'Rasool AHMED', 'Swat', '1949-01-24');